version: '3'
services:
  app:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_PASSWORD: yourpassword
      DB_NAME: warehouse
      DB_HOST: db
      DB_PORT: 5432
  db:
    restart: always
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: warehouse
    ports:
      - "5432:5432"