version: '3'
services:
  app:
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      db:
       condition: service_healthy
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: yourpassword
      DB_NAME: warehouse
      DB_HOST: db
      DB_PORT: 5432
      PORT: 8080
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5
  db:
    restart: always
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: warehouse
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 5